12:21:55 [DBHandler]  MainThread:{4662875584} [__init__()]   INFO 
 DBHandler was started in ThreadSafeMode. 

12:21:55 [DBHandler]  MainThread:{4662875584} [_validate_statsDB()]  ERROR 
 StatsDBValidationError: Given Stats-DB contain not correct attributes. Following col_and_types was extracted: '[(u'id', u'INTEGER'), (u'corpus_id', u'INTEGER'), (u'name', u'TEXT'), (u'version', u'TEXT'), (u'created_at', u'TEXT'), (u'visibility', u'TEXT'), (u'typ', u'TEXT'), (u'db_frozen', u'INTEGER'), (u'context_lenght', u'INTEGER'), (u'language', u'TEXT'), (u'repl_up', u'INTEGER'), (u'ignore_hashtag', u'INTEGER'), (u'ignore_url', u'INTEGER'), (u'ignore_mention', u'INTEGER'), (u'ignore_punkt', u'INTEGER'), (u'ignore_num', u'INTEGER'), (u'force_cleaning', u'INTEGER'), (u'case_sensitiv', u'INTEGER'), (u'full_repetativ_syntagma', u'INTEGER'), (u'min_scope_for_indexes', u'INTEGER'), (u'locked', u'INTEGER'), (u'pos_tagger', u'TEXT'), (u'sentiment_analyzer', u'TEXT')]' and they are incorrect. Please use following data as golden standard: '[('id', 'INTEGER'), ('corpus_id', 'INTEGER'), ('name', 'TEXT'), ('version', 'TEXT'), ('created_at', 'TEXT'), ('visibility', 'TEXT'), ('typ', 'TEXT'), ('db_frozen', 'INTEGER'), ('context_lenght', 'INTEGER'), ('language', 'TEXT'), ('repl_up', 'INTEGER'), ('ignore_hashtag', 'INTEGER'), ('ignore_url', 'INTEGER'), ('ignore_mention', 'INTEGER'), ('ignore_punkt', 'INTEGER'), ('ignore_num', 'INTEGER'), ('force_cleaning', 'INTEGER'), ('case_sensitiv', 'INTEGER'), ('full_repetativ_syntagma', 'INTEGER'), ('min_scope_for_indexes', 'INTEGER'), ('locked', 'INTEGER'), ('pos_tagger', 'TEXT'), ('sentiment_analyzer', 'TEXT'), ('baseline_delimiter', 'TEXT')]'.  

     [35mNone
[0m




12:21:55 [DBHandler]  MainThread:{4662875584} [_validation_DBfile()]  WARNING 
 Validator is failed! Connected/Attached DB can not be used. Please choice another one. 

12:21:55 [Stats]  MainThread:{4662875584} [open()]  ERROR 
 StatsOpener: Unfortunately '7728_4292_stats_sifter_de_intern_plaintext.db'-Stats wasn't opened. 

     [35mNone
[0m




12:21:55 [CLI]  MainThread:{4662875584} [stats()]  ERROR 
 '7728_4292_stats_sifter_de_intern_plaintext.db'-DB wasn't opened. Possibly this DB is damaged or encrypted or locked. Please use '--encryption_key' option to set an encryption_key  

